import 'package:flutter/material.dart';

class TextExample extends StatelessWidget {
  const TextExample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Text(
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis et leo rhoncus, mollis justo id, mattis lorem. Fusce vel lorem laoreet, pretium libero nec, finibus risus. Duis auctor elit sit amet augue dignissim suscipit. In aliquet velit lobortis turpis tristique congue. Mauris orci odio, vestibulum vel viverra in, rutrum sed mauris. Aliquam tempor lacinia est, sed ullamcorper ante tempus id. Phasellus quis felis ante. Phasellus molestie urna ante, ac sollicitudin est lobortis sed. Ut interdum tortor libero, quis auctor nunc fringilla sed. Ut consectetur et lorem eget scelerisque. Vivamus sed euismod nequeDuis dapibus risus erat, ac consequat tellus faucibus tristique. Vivamus vitae libero tortor. Mauris gravida venenatis nulla sit amet sollicitudin. Suspendisse dignissim lacus tellus, sed eleifend metus scelerisque euismod. Quisque in pretium magna. Pellentesque placerat est id turpis molestie, ut mollis enim venenatis. Nam eu erat a odio dictum pellentesque in a risus. In placerat, elit vitae sollicitudin aliquet, mauris augue placerat magna, vitae malesuada tortor orci ultricies nulla. Maecenas lobortis urna urna, sed aliquet erat egestas utIn dapibus augue a ullamcorper auctor. Proin efficitur commodo varius. Nulla imperdiet elit eget sem efficitur gravida. Donec lobortis arcu laoreet sapien molestie aliquam. Quisque luctus ex quis augue interdum maximus. Phasellus quis lorem magna. Donec ultricies pharetra interdumMorbi ex sem, vehicula vel tempor nec, sodales a orci. Curabitur in dignissim turpis, sit amet pharetra ipsum. Proin maximus molestie quam, in malesuada ex faucibus nec. Phasellus mattis fermentum leo eu placerat. Vivamus vitae imperdiet magna. Integer pulvinar ac sapien sit amet consequat. Morbi vulputate ut arcu ut ullamcorper. Suspendisse potenti. Sed gravida ex id nulla ultrices eleifend. Suspendisse elementum et magna nec laoreet. Phasellus augue orci, tincidunt non dignissim sit amet, feugiat sit amet elit. Proin ac nisl in lacus aliquet cursus in nec Nullam cursus, orci nec laoreet hendrerit, mauris dui consequat diam, sit amet egestas mi tortor id ex. Cras id ipsum diam. Maecenas lacinia magna at elit cursus posuere. Pellentesque urna sapien, semper at sagittis in, auctor et ante. Duis consectetur lectus quam, quis interdum felis mattis a. Sed nec suscipit tortor, ut dignissim turpis. Nulla fermentum quam massa, ac tristique erat vehicula vitae. Pellentesque ut purus aliquet risus vulputate rutrum. Suspendisse in libero ornare, mollis nisi condimentum, volutpat ex. In vitae tristique augue. Nulla eget lorem congue, facilisis purus ac, hendrerit justo. Morbi in vulputate sapien, non vestibulum urna.');
  }
}
